export const books = [
  {
    id: "1",
    title: "教育 (Education)",
    author: "遠野 遥 (Haruka Tono)",
    cover: "/books/cover/education.jpeg",
    description: "Novel Jepang yang mengeksplorasi tema pendidikan dan identitas.",
    category: "fiction",
  },
  {
    id: "2",
    title: "They Lost",
    author: "Matt Zhang",
    cover: "/books/cover/theylost.png",
    description: "Sebuah thriller internasional penuh ketegangan dan misteri.",
    category: "thriller",
  },
  {
    id: "3",
    title: "Black Clover",
    author: "Unknown",
    cover: "/books/cover/black_clover.jpeg",
    description: "Sebuah buku misterius bergaya grimoire kuno dengan simbol-simbol magis.",
    category: "fantasy",
  },
  {
    id: "4",
    title: "何食わぬきみたちへ",
    author: "新胡桃 (Arata Kurumi)",
    cover: "/books/cover/nanikuwanu.jpeg",
    description: "Novel dengan gaya artistik yang mendalam, penuh misteri psikologis.",
    category: "psychological",
  },
    {
    id: "5",
    title: "The Last Royal Dragon",
    author: "David Gardias",
    cover: "/books/cover/last_royal_dragon.jpeg",
    description: "Kisah epik fantasi tentang naga terakhir dan kerajaan yang terancam.",
    category: "fantasy",
  },
  {
    id: "6",
    title: "The Legend of Skeleton Man",
    author: "Joseph Bruchac",
    cover: "/books/cover/skeleton_man.jpeg",
    description: "Legenda horor tentang sosok misterius Skeleton Man yang menghantui sebuah keluarga.",
    category: "horror",
  },
  {
    id: "7",
    title: "Sea Smoke",
    author: "Allison Carr Waechter",
    cover: "/books/cover/sea_smoke.jpeg",
    description: "Novel fantasi atmosferik berlatar dunia bersalju, penuh misteri dan sihir.",
    category: "fantasy",
  },
  {
    id: "8",
    title: "飛と龍子 (Tobi and Ryuko)",
    author: "Eve",
    cover: "/books/cover/tobi_ryuko.jpeg",
    description: "Manga tentang kehidupan sehari-hari yang penuh warna dengan sentuhan fantasi.",
    category: "manga",
  },
];
